select * 
from tb_estoque;

create view VW_ESTOQUE_LIMPO as
select ID_PROD
      ,UPPER(LTRIM(RTRIM(NOME_PROD))) AS NOME_PRODUTO  
      ,UPPER (LTRIM(RTRIM(LOJA_FILIAL))) AS LOJA
      ,UPPER (LTRIM(RTRIM(ADULTO_INFANTIL))) AS PUBLICO 
      ,UPPER (LTRIM(RTRIM(GENERO))) as GENERO
      ,NUMERACAO_CALC AS NUMERACAO          
      ,UPPER(LTRIM(RTRIM(COLEÇÃO))) AS COLECAO
      ,CAST(VALOR_UNITARIO AS DECIMAL(10,2)) AS VALOR_UNITARIO
      ,CAST(VALOR_REPASSE AS DECIMAL(10,2)) AS VALOR_REPASSE
      ,ENTRADA_ESTOQUE
      ,TOTAL_DE_SAIDA 
      ,(ENTRADA_ESTOQUE - TOTAL_DE_SAIDA) AS QTD_ATUAL
      ,DATA_ENTRADA
      ,DATA_ULTIMA_SAIDA
from tb_estoque


select * 
from VW_ESTOQUE_LIMPO;

create view VW_ESTOQUE_GENERO AS
select GENERO
      ,SUM(TOTAL_DE_SAIDA) AS QTD_SAIDAS           
from VW_ESTOQUE_LIMPO
group by GENERO

select * 
from VW_ESTOQUE_GENERO;



create view VW_ESTOQUE_COLECAO AS
select COLECAO
      ,SUM(TOTAL_DE_SAIDA) AS QTD_SAIDAS           
from VW_ESTOQUE_LIMPO
group by COLECAO

select * 
from VW_ESTOQUE_COLECAO;



